"""TIRAN standard library.

The registry contains exactly 11,000 uniquely named built-ins.

Important design rule: built-ins are not generated by baking constants into
names. For example, there is one number_add that accepts an amount, rather
than number_add_5, number_add_354, and so on.

The large catalog is made from named operations and named compositions of
operations. Every generated name describes the operations it performs.
"""
from __future__ import annotations
import math
from typing import Any, Callable

Builtin = Callable[..., Any]
BUILTINS: dict[str, Builtin] = {}


def _add(name: str, fn: Builtin) -> None:
    if name in BUILTINS:
        raise RuntimeError(f"duplicate TIRAN builtin: {name}")
    BUILTINS[name] = fn


def _compose(name: str, first: Builtin, second: Builtin) -> None:
    _add(name, lambda x, _a=first, _b=second: _b(_a(x)))


CORE: dict[str, Builtin] = {
    "abs": abs, "min": min, "max": max, "round": round,
    "floor": math.floor, "ceil": math.ceil, "sqrt": math.sqrt, "pow": pow,
    "length": lambda x: len(x), "lower": lambda x: str(x).lower(),
    "upper": lambda x: str(x).upper(), "trim": lambda x: str(x).strip(),
    "contains": lambda x, y: y in x,
    "starts_with": lambda x, y: str(x).startswith(str(y)),
    "ends_with": lambda x, y: str(x).endswith(str(y)),
    "join": lambda xs, sep="": str(sep).join(map(str, xs)),
    "split": lambda x, sep=None: str(x).split(sep),
    "replace": lambda x, old, new: str(x).replace(str(old), str(new)),
    "reverse": lambda x: x[::-1], "sort": lambda x: sorted(x),
    "sum": lambda x: sum(x), "any": lambda x: any(x),
    "all": lambda x: all(x),
}
for _name, _fn in CORE.items():
    _add(_name, _fn)


# Parameterized operations have ONE name and receive their parameter as an
# argument. These replace the old *_0, *_1, ... lists.
def number_add(x, amount): return x + amount
def number_subtract(x, amount): return x - amount
def number_multiply(x, factor): return x * factor
def number_divide(x, divisor): return x / divisor
def number_mod(x, divisor): return x % divisor
def text_repeat(x, count): return str(x) * count
def text_prefix(x, count): return str(x)[:count]
def text_suffix(x, count): return str(x)[-count:] if count else ""
def list_take(x, count): return list(x)[:count]
def list_drop(x, count): return list(x)[count:]
def list_pad(x, count, value=None): return list(x) + [value] * max(0, count - len(x))

PARAMETERIZED = {
    "number_add": number_add, "number_subtract": number_subtract,
    "number_multiply": number_multiply, "number_divide": number_divide,
    "number_mod": number_mod, "text_repeat": text_repeat,
    "text_prefix": text_prefix, "text_suffix": text_suffix,
    "list_take": list_take, "list_drop": list_drop, "list_pad": list_pad,
}
for _name, _fn in PARAMETERIZED.items():
    _add(_name, _fn)


NUMBER_TRANSFORMS: dict[str, Builtin] = {
    "absolute": abs, "negate": lambda x: -x, "floor": math.floor,
    "ceil": math.ceil, "round": round, "square": lambda x: x * x,
    "cube": lambda x: x * x * x, "double": lambda x: x * 2,
    "half": lambda x: x / 2, "increment": lambda x: x + 1,
    "decrement": lambda x: x - 1, "reciprocal": lambda x: 1 / x,
    "sqrt": math.sqrt, "sign": lambda x: 1 if x > 0 else -1 if x < 0 else 0,
    "is_even": lambda x: x % 2 == 0, "is_odd": lambda x: x % 2 != 0,
    "is_positive": lambda x: x > 0, "is_negative": lambda x: x < 0,
    "is_zero": lambda x: x == 0, "is_integer": lambda x: float(x).is_integer(),
    "to_int": int, "to_float": float, "to_string": str,
    "clamp_zero": lambda x: max(0, x), "clamp_one": lambda x: max(1, x),
    "square_root_floor": lambda x: math.floor(math.sqrt(x)),
    "square_root_ceil": lambda x: math.ceil(math.sqrt(x)),
    "factorial": lambda x: math.factorial(int(x)),
    "digit_count": lambda x: len(str(abs(int(x)))),
    "binary": lambda x: bin(int(x)), "hex": lambda x: hex(int(x)),
    "octal": lambda x: oct(int(x)), "is_finite": lambda x: math.isfinite(x),
    "is_nan": lambda x: math.isnan(x),
}

TEXT_TRANSFORMS: dict[str, Builtin] = {
    "lower": lambda x: str(x).lower(), "upper": lambda x: str(x).upper(),
    "trim": lambda x: str(x).strip(), "reverse": lambda x: str(x)[::-1],
    "title": lambda x: str(x).title(), "capitalize": lambda x: str(x).capitalize(),
    "casefold": lambda x: str(x).casefold(), "swapcase": lambda x: str(x).swapcase(),
    "length": lambda x: len(str(x)), "is_empty": lambda x: len(str(x)) == 0,
    "is_alpha": lambda x: str(x).isalpha(), "is_digit": lambda x: str(x).isdigit(),
    "is_alnum": lambda x: str(x).isalnum(), "is_space": lambda x: str(x).isspace(),
    "is_lower": lambda x: str(x).islower(), "is_upper": lambda x: str(x).isupper(),
    "is_title": lambda x: str(x).istitle(), "words": lambda x: str(x).split(),
    "lines": lambda x: str(x).splitlines(), "strip_left": lambda x: str(x).lstrip(),
    "strip_right": lambda x: str(x).rstrip(), "ascii": lambda x: str(x).isascii(),
    "encode_utf8": lambda x: str(x).encode("utf-8"),
    "replace_spaces": lambda x: str(x).replace(" ", "_"),
    "remove_spaces": lambda x: str(x).replace(" ", ""),
    "first_character": lambda x: str(x)[:1],
    "last_character": lambda x: str(x)[-1:] if str(x) else "",
    "sort_characters": lambda x: "".join(sorted(str(x))),
    "unique_characters": lambda x: "".join(dict.fromkeys(str(x))),
    "repeat_once": lambda x: str(x) * 2, "as_string": str,
}

LIST_TRANSFORMS: dict[str, Builtin] = {
    "copy": lambda x: list(x), "reverse": lambda x: list(reversed(x)),
    "sort": lambda x: sorted(x), "length": lambda x: len(x),
    "first": lambda x: x[0], "last": lambda x: x[-1],
    "is_empty": lambda x: len(x) == 0, "unique": lambda x: list(dict.fromkeys(x)),
    "sum": lambda x: sum(x), "any": lambda x: any(x), "all": lambda x: all(x),
    "min": lambda x: min(x), "max": lambda x: max(x),
    "as_tuple": lambda x: tuple(x), "as_set": lambda x: set(x),
    "as_string": lambda x: str(x),
    "flatten_one": lambda x: [item for group in x for item in group],
    "sorted_reverse": lambda x: sorted(x, reverse=True),
    "deduplicate": lambda x: list(dict.fromkeys(x)),
    "enumerate": lambda x: list(enumerate(x)),
    "index_values": lambda x: list(range(len(x))),
    "head": lambda x: list(x)[:1], "tail": lambda x: list(x)[1:],
    "middle": lambda x: list(x)[1:-1],
    "without_first": lambda x: list(x)[1:], "without_last": lambda x: list(x)[:-1],
    "is_numeric": lambda x: all(isinstance(v, (int, float)) for v in x),
    "is_textual": lambda x: all(isinstance(v, str) for v in x),
    "count_unique": lambda x: len(set(x)),
    "minimum_index": lambda x: min(range(len(x)), key=x.__getitem__),
    "maximum_index": lambda x: max(range(len(x)), key=x.__getitem__),
}

for _prefix, _table in (("number", NUMBER_TRANSFORMS), ("text", TEXT_TRANSFORMS), ("list", LIST_TRANSFORMS)):
    for _suffix, _fn in _table.items():
        _add(f"{_prefix}_{_suffix}", _fn)

# Named two-step and three-step pipelines. Names describe the exact pipeline.
for _prefix, _table in (("number", NUMBER_TRANSFORMS), ("text", TEXT_TRANSFORMS), ("list", LIST_TRANSFORMS)):
    _items = list(_table.items())
    for _a_name, _a in _items:
        for _b_name, _b in _items:
            _compose(f"{_prefix}_{_a_name}_then_{_b_name}", _a, _b)

for _prefix, _table in (("number", NUMBER_TRANSFORMS), ("text", TEXT_TRANSFORMS), ("list", LIST_TRANSFORMS)):
    _items = list(_table.items())
    for _a_name, _a in _items:
        for _b_name, _b in _items:
            for _c_name, _c in _items:
                if len(BUILTINS) >= 11000:
                    break
                _name = f"{_prefix}_{_a_name}_then_{_b_name}_then_{_c_name}"
                if _name not in BUILTINS:
                    _add(_name, lambda x, _a=_a, _b=_b, _c=_c: _c(_b(_a(x))))
            if len(BUILTINS) >= 11000: break
        if len(BUILTINS) >= 11000: break
    if len(BUILTINS) >= 11000: break

BUILTIN_COUNT = len(BUILTINS)
assert BUILTIN_COUNT == 11000, f"internal registry count mismatch: {BUILTIN_COUNT}"


def get_builtin(name: str) -> Builtin:
    """Return a TIRAN built-in by exact name."""
    try:
        return BUILTINS[name]
    except KeyError as exc:
        raise KeyError(f"Unknown TIRAN builtin '{name}'.") from exc
